{
 "title": "HB Monitor R26",
 "description": "Monitoring HB Inference Server",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(vllm:cache_config_info,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "HB serve INFO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Model Name",
   "type": "stat",
   "description": "模型名称",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vllm:cache_config_info{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Token Numbers",
   "type": "stat",
   "description": "显存可容纳的token数量。",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vllm:cache_config_info{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prefix Cache",
   "type": "stat",
   "description": "是否开启prefix cache功能。",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vllm:cache_config_info{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    { "expr": "vllm:cache_config_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU Memory Util",
   "type": "stat",
   "description": "用于存储模型权重、kv cache、计算中间结果所需GPU显存的百分比。",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vllm:cache_config_info{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    { "expr": "vllm:cache_config_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Numbers",
   "type": "timeseries",
   "description": "length finished  and stop finished.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "clamp_min(vllm:request_success_total{finished_reason=\"length\", instance=\"$instance\"} - vllm:request_success_total{finished_reason=\"length\", instance=\"$instance\"} offset 15s, 0)",
     "legendFormat": "Length"
    },
    {
     "expr": "clamp_min(vllm:request_success_total{finished_reason=\"stop\", instance=\"$instance\"} - vllm:request_success_total{finished_reason=\"stop\", instance=\"$instance\"} offset 15s, 0)",
     "legendFormat": "Stop"
    },
    {
     "expr": "sum by(model_name)(clamp_min(hb_serve:request_total{instance=\"$instance\"} - hb_serve:request_total{instance=\"$instance\"} offset 15s, 0))",
     "legendFormat": "{{model_name}} request"
    },
    {
     "expr": "clamp_min(hb_serve:request_fail_guided_total{instance=\"$instance\"} - hb_serve:request_fail_guided_total{instance=\"$instance\"} offset 15s, 0)",
     "legendFormat": "guided error "
    },
    {
     "expr": "clamp_min(hb_serve:request_fail_length_total{instance=\"$instance\"} - hb_serve:request_fail_length_total{instance=\"$instance\"} offset 15s, 0)",
     "legendFormat": "token length error "
    },
    {
     "expr": "clamp_min(hb_serve:request_fail_model_total{instance=\"$instance\"} - hb_serve:request_fail_model_total{instance=\"$instance\"} offset 15s, 0)",
     "legendFormat": "model name error "
    },
    {
     "expr": "clamp_min(hb_serve:request_fail_connection_total{instance=\"$instance\"} - hb_serve:request_fail_connection_total{instance=\"$instance\"} offset 6h, 0)",
     "legendFormat": "client disconnection"
    },
    {
     "expr": "clamp_min(hb_serve:request_fail_header_total{instance=\"$instance\"} - hb_serve:request_fail_header_total{instance=\"$instance\"} offset 15s, 0)",
     "legendFormat": "header error"
    },
    {
     "expr": "clamp_min(hb_serve:request_fail_other_total{instance=\"$instance\"} - hb_serve:request_fail_other_total{instance=\"$instance\"} offset 15s, 0)",
     "legendFormat": "other error"
    },
    {
     "expr": "sum(clamp_min(hb_serve:request_total{instance=\"$instance\"} - hb_serve:request_total{instance=\"$instance\"} offset 15s, 0))",
     "legendFormat": "request total"
    },
    {
     "expr": "clamp_min(sum by(reasoning, model_name) (hb_serve:request_total{instance=\"$instance\"}) - sum by(reasoning, model_name)(hb_serve:request_total{instance=\"$instance\"} offset 15s), 0)",
     "legendFormat": "{{model_name}}-think-{{reasoning}} request"
    }
   ]
  },
  {
   "title": "Succes Request Numbers",
   "type": "timeseries",
   "description": "length finished  and stop finished.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum by(model_name)(clamp_min(vllm:generation_tokens_total{instance=\"$instance\"} - vllm:generation_tokens_total{instance=\"$instance\"} offset 15s, 0))",
     "legendFormat": "generation_tokens-{{model_name}}"
    },
    {
     "expr": "sum by(model_name)(clamp_min(vllm:prompt_tokens_total{instance=\"$instance\"} - vllm:prompt_tokens_total{instance=\"$instance\"} offset 15s, 0))",
     "legendFormat": "prompt tokens-{{model_name}}"
    }
   ]
  },
  {
   "title": "Succes Request Numbers",
   "type": "timeseries",
   "description": "length finished  and stop finished.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by(model_name)(clamp_min(vllm:num_preemptions_total{instance=\"$instance\"} - vllm:num_preemptions_total{instance=\"$instance\"} offset 15s, 0))",
     "legendFormat": "{{model_name}} Num Preemptions Total"
    }
   ]
  },
  {
   "title": "Cached token bug Number",
   "type": "timeseries",
   "description": "因为prefix caching在高并发下导致的cached token bug的请求数量。",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "clamp_min(vllm:number_cached_token_error_seq_total{instance=\"$instance\"} - vllm:number_cached_token_error_seq_total{instance=\"$instance\"} offset 15s, 0)",
     "legendFormat": "bug request number"
    }
   ]
  },
  {
   "title": "GPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Utilization",
     "type": "timeseries",
     "description": "GPU的计算单元综合利用率。",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "DCGM_FI_DEV_GPU_UTIL{}", "legendFormat": "GPU {{gpu}}" }
     ]
    },
    {
     "title": "GPU Mem Copy Utilization",
     "type": "timeseries",
     "description": "GPU显存带宽利用率",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "DCGM_FI_DEV_MEM_COPY_UTIL", "legendFormat": "GPU {{gpu}}" }
     ]
    },
    {
     "title": "GPU Temperature",
     "type": "timeseries",
     "description": "GPU CUDA核温度。",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      { "expr": "DCGM_FI_DEV_GPU_TEMP", "legendFormat": "GPU {{gpu}}" }
     ]
    },
    {
     "title": "GPU Power",
     "type": "timeseries",
     "description": "GPU功耗",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      { "expr": "DCGM_FI_DEV_POWER_USAGE", "legendFormat": "GPU {{gpu}}" }
     ]
    },
    {
     "title": "GPU Framebuffer Mem Used",
     "type": "timeseries",
     "description": "显存使用。",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      { "expr": "DCGM_FI_DEV_FB_USED{}", "legendFormat": "GPU {{gpu}}" }
     ]
    },
    {
     "title": "GPU Framebuffer Mem Free",
     "type": "timeseries",
     "description": "显存空闲。",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      { "expr": "DCGM_FI_DEV_FB_FREE{}", "legendFormat": "GPU {{gpu}}" }
     ]
    },
    {
     "title": "PICE Rate Received",
     "type": "timeseries",
     "description": "The rate of data received over the PCIe bus - including both protocol headers and data payloads - in bytes per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      { "expr": "DCGM_FI_PROF_PCIE_RX_BYTES", "legendFormat": "GPU{{gpu}}" }
     ]
    },
    {
     "title": "PICE Rate Transmitted",
     "type": "timeseries",
     "description": "The rate of data transmitted over the PCIe bus - including both protocol headers and data payloads - in bytes per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      { "expr": "DCGM_FI_PROF_PCIE_TX_BYTES", "legendFormat": "GPU{{gpu}}" }
     ]
    },
    {
     "title": "Mem Clock",
     "type": "timeseries",
     "description": "显存时钟。",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "targets": [
      { "expr": "DCGM_FI_DEV_MEM_CLOCK", "legendFormat": "GPU {{gpu}}" }
     ]
    },
    {
     "title": "SM Clock",
     "type": "timeseries",
     "description": "计算单元时钟。",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "targets": [
      { "expr": "DCGM_FI_DEV_SM_CLOCK", "legendFormat": "GPU {{gpu}}" }
     ]
    }
   ]
  },
  { "title": "HB serve", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Scheduler State",
   "type": "timeseries",
   "description": "Number of requests in RUNNING, WAITING, and SWAPPED state",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "vllm:num_requests_running{instance=\"$instance\"}",
     "legendFormat": "Num Running"
    },
    {
     "expr": "vllm:num_requests_waiting{instance=\"$instance\"}",
     "legendFormat": "Num Waiting"
    }
   ]
  },
  {
   "title": "Cache Utilization",
   "type": "timeseries",
   "description": "Percentage of used cache blocks by vLLM.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "vllm:kv_cache_usage_perc{instance=\"$instance\"}",
     "legendFormat": "KV Cache Usage"
    }
   ]
  },
  {
   "title": "Time To First Token Latency",
   "type": "timeseries",
   "description": "P50, P90, P95, and P99 TTFT latency in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "rate(vllm:time_to_first_token_seconds_sum{instance=\"$instance\"}[$__rate_interval]) / rate(vllm:time_to_first_token_seconds_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Time Per Output Token Latency",
   "type": "timeseries",
   "description": "Inter token latency in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:request_time_per_output_token_seconds_bucket{instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:request_time_per_output_token_seconds_bucket{instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:request_time_per_output_token_seconds_bucket{instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:request_time_per_output_token_seconds_bucket{instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "rate(vllm:request_time_per_output_token_seconds_sum{instance=\"$instance\"}[$__rate_interval]) / rate(vllm:request_time_per_output_token_seconds_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Request Prompt Length",
   "type": "heatmap",
   "description": "Heatmap of request prompt length",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by(le) (increase(vllm:request_prompt_tokens_bucket{instance=\"$instance\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Generation Length",
   "type": "heatmap",
   "description": "Heatmap of request generation length",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "sum by(le) (increase(vllm:request_generation_tokens_bucket{instance=\"$instance\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "E2E Request Latency",
   "type": "timeseries",
   "description": "End to end request latency measured in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "rate(vllm:e2e_request_latency_seconds_sum{instance=\"$instance\"}[$__rate_interval]) / rate(vllm:e2e_request_latency_seconds_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Finish Reason",
   "type": "timeseries",
   "description": "Number of finished requests by their finish reason: either an EOS token was generated or the max sequence length was reached.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "sum by(finished_reason) (increase(vllm:request_success_total{instance=\"$instance\"}[15s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Token Throughput",
   "type": "timeseries",
   "description": "Number of tokens processed per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "rate(vllm:prompt_tokens_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Prompt Tokens/Sec"
    },
    {
     "expr": "rate(vllm:generation_tokens_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Generation Tokens/Sec"
    }
   ]
  },
  {
   "title": "Prefix Cache Hit Rate",
   "type": "timeseries",
   "description": "Percentage of used cache blocks by vLLM.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "vllm:prefix_cache_hits_total{instance=\"$instance\"}",
     "legendFormat": "Prefix Cache Hit total"
    },
    {
     "expr": "vllm:prefix_cache_queries_total",
     "legendFormat": "prefix_cache_queries_total"
    }
   ]
  },
  {
   "title": "Guided Decode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Numbers",
     "type": "timeseries",
     "description": "GD request numbers",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "clamp_min(vllm:guided_decode_num_compiled_success_total{instance=\"$instance\"} - vllm:guided_decode_num_compiled_success_total{instance=\"$instance\"} offset 15s, 0)",
       "legendFormat": "compile success num"
      },
      {
       "expr": "clamp_min(vllm:guided_decode_num_compilation_errors_total{instance=\"$instance\"}- vllm:guided_decode_num_compilation_errors_total{instance=\"$instance\"} offset 15s, 0)",
       "legendFormat": "compile grammar error num"
      },
      {
       "expr": "clamp_min(vllm:guided_decode_num_compilation_timeouts_total{instance=\"$instance\"}- vllm:guided_decode_num_compilation_timeouts_total{instance=\"$instance\"} offset 15s, 0)",
       "legendFormat": "compile timeout num"
      },
      {
       "expr": "clamp_min(vllm:guided_decode_num_compilations_rejected_with_concurrency_total{instance=\"$instance\"}- vllm:guided_decode_num_compilations_rejected_with_concurrency_total{instance=\"$instance\"} offset 15s, 0)",
       "legendFormat": "compile concurrency limit num"
      }
     ]
    },
    {
     "title": "Compile Latency",
     "type": "timeseries",
     "description": "End to end request latency measured in seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:guided_decode_compilation_time_bucket{instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:guided_decode_compilation_time_bucket{instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:guided_decode_compilation_time_bucket{instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "P90"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:guided_decode_compilation_time_bucket{instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "P50"
      },
      {
       "expr": "rate(vllm:guided_decode_compilation_time_sum{instance=\"$instance\"}[$__rate_interval]) / rate(vllm:guided_decode_compilation_time_count{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Average"
      },
      {
       "expr": "vllm:guided_compilation_timeout{instance=\"$instance\"}",
       "legendFormat": "Timeout"
      }
     ]
    },
    {
     "title": "Compile State",
     "type": "timeseries",
     "description": "Compile concurrency number",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "vllm:guided_decode_num_compiling{instance=\"$instance\"}",
       "legendFormat": "Num Compiling"
      },
      {
       "expr": "vllm:guided_decode_num_of_waiting{instance=\"$instance\"}",
       "legendFormat": "Num Waiting"
      }
     ]
    }
   ]
  }
 ]
}